/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./../.vitepress/vp/components/icons/back-to-top.vue')['default']
    Codepen: typeof import('./../.vitepress/vp/components/icons/codepen.vue')['default']
    Dark: typeof import('./../.vitepress/vp/components/icons/dark.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElementPlusLogo: typeof import('./../.vitepress/vp/components/icons/element-plus-logo.vue')['default']
    ElementPlusTextLogo: typeof import('./../.vitepress/vp/components/icons/element-plus-text-logo.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Expand: typeof import('./../.vitepress/vp/components/icons/expand.vue')['default']
    Light: typeof import('./../.vitepress/vp/components/icons/light.vue')['default']
    Playground: typeof import('./../.vitepress/vp/components/icons/playground.vue')['default']
    ToggleButton: typeof import('./../.vitepress/vp/components/icons/toggle-button.vue')['default']
    VpApp: typeof import('./../.vitepress/vp/components/vp-app.vue')['default']
    VpHamburger: typeof import('./../.vitepress/vp/components/navbar/vp-hamburger.vue')['default']
    VpLink: typeof import('./../.vitepress/vp/components/common/vp-link.vue')['default']
    VpMenu: typeof import('./../.vitepress/vp/components/navbar/vp-menu.vue')['default']
    VpMenuLink: typeof import('./../.vitepress/vp/components/navbar/vp-menu-link.vue')['default']
    VpNav: typeof import('./../.vitepress/vp/components/vp-nav.vue')['default']
    VpNavbar: typeof import('./../.vitepress/vp/components/vp-navbar.vue')['default']
    VpNavMd: typeof import('./../.vitepress/vp/components/vp-nav-md.vue')['default']
    VpSocialLinks: typeof import('./../.vitepress/vp/components/navbar/vp-social-links.vue')['default']
    VpThemeToggle: typeof import('./../.vitepress/vp/components/common/vp-theme-toggle.vue')['default']
    VpThemeToggler: typeof import('./../.vitepress/vp/components/common/vp-theme-toggler.vue')['default']
  }
}
